#pragma once

#include <string_view>

#include "beatsaber-hook/shared/utils/typedefs.h"

#if __has_include("bsml/shared/Helpers/utilities.hpp")
#include "bsml/shared/Helpers/utilities.hpp"
#endif

struct IncludedAsset {
    IncludedAsset(uint8_t* start, uint8_t* end) : array(reinterpret_cast<Array<uint8_t>*>(start)) {
        array->klass = nullptr;
        array->monitor = nullptr;
        array->bounds = nullptr;
        array->max_length = end - start - 32;
        *(end - 1) = '\0';
    }

    operator ArrayW<uint8_t>() const {
        init();
        return array;
    }

    operator std::string_view() const {
        return {reinterpret_cast<char*>(array->_values), array->get_Length()};
    }

    operator std::span<uint8_t>() const {
        return {array->_values, array->get_Length()};
    }

    void init() const {
        if (!array->klass) {
            array->klass = classof(Array<uint8_t>*);
        }
    }

   private:
    Array<uint8_t>* array;
};

#define PNG_SPRITE(asset) BSML::Utilities::LoadSpriteRaw(static_cast<ArrayW<uint8_t>>(asset))

/**
 * Namespace containing all embedded assets.
 */
namespace IncludedAssets {
    /**
    * @brief Contains raw asset symbols generated by llvm-objcopy.
    * This namespace is private and should not be used directly.
    */
    namespace __AssetExterns__ {
        extern "C" uint8_t _binary_download_modal_bsml_start[];
        extern "C" uint8_t _binary_download_modal_bsml_end[];
        extern "C" uint8_t _binary_download_modal_bsml_size[];
        extern "C" uint8_t _binary_file_actions_modal_bsml_start[];
        extern "C" uint8_t _binary_file_actions_modal_bsml_end[];
        extern "C" uint8_t _binary_file_actions_modal_bsml_size[];
        extern "C" uint8_t _binary_imager_library_bsml_start[];
        extern "C" uint8_t _binary_imager_library_bsml_end[];
        extern "C" uint8_t _binary_imager_library_bsml_size[];
        extern "C" uint8_t _binary_placement_position_modal_bsml_start[];
        extern "C" uint8_t _binary_placement_position_modal_bsml_end[];
        extern "C" uint8_t _binary_placement_position_modal_bsml_size[];
        extern "C" uint8_t _binary_placement_settings_bsml_start[];
        extern "C" uint8_t _binary_placement_settings_bsml_end[];
        extern "C" uint8_t _binary_placement_settings_bsml_size[];
        extern "C" uint8_t _binary_placement_size_modal_bsml_start[];
        extern "C" uint8_t _binary_placement_size_modal_bsml_end[];
        extern "C" uint8_t _binary_placement_size_modal_bsml_size[];
        extern "C" uint8_t _binary_placement_visibility_modal_bsml_start[];
        extern "C" uint8_t _binary_placement_visibility_modal_bsml_end[];
        extern "C" uint8_t _binary_placement_visibility_modal_bsml_size[];
        extern "C" uint8_t _binary_rotation_modal_bsml_start[];
        extern "C" uint8_t _binary_rotation_modal_bsml_end[];
        extern "C" uint8_t _binary_rotation_modal_bsml_size[];
        extern "C" uint8_t _binary_settings_bsml_start[];
        extern "C" uint8_t _binary_settings_bsml_end[];
        extern "C" uint8_t _binary_settings_bsml_size[];
    }  // namespace __AssetExterns__

    /**
     * Binary asset representing the file "download_modal.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset download_modal_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_download_modal_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_download_modal_bsml_end
    };
    
    /**
     * Binary asset representing the file "file_actions_modal.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset file_actions_modal_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_file_actions_modal_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_file_actions_modal_bsml_end
    };
    
    /**
     * Binary asset representing the file "imager_library.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset imager_library_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_imager_library_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_imager_library_bsml_end
    };
    
    /**
     * Binary asset representing the file "placement_position_modal.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset placement_position_modal_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_placement_position_modal_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_placement_position_modal_bsml_end
    };
    
    /**
     * Binary asset representing the file "placement_settings.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset placement_settings_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_placement_settings_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_placement_settings_bsml_end
    };
    
    /**
     * Binary asset representing the file "placement_size_modal.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset placement_size_modal_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_placement_size_modal_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_placement_size_modal_bsml_end
    };
    
    /**
     * Binary asset representing the file "placement_visibility_modal.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset placement_visibility_modal_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_placement_visibility_modal_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_placement_visibility_modal_bsml_end
    };
    
    /**
     * Binary asset representing the file "rotation_modal.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset rotation_modal_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_rotation_modal_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_rotation_modal_bsml_end
    };
    
    /**
     * Binary asset representing the file "settings.bsml".
     * Embedded with love (and a little objcopy magic), mmkay?
     */
    const IncludedAsset settings_bsml {
        ::IncludedAssets::__AssetExterns__::_binary_settings_bsml_start,
        ::IncludedAssets::__AssetExterns__::_binary_settings_bsml_end
    };
}  // namespace IncludedAssets
